### ISSUE TITLE
Creators update Breaks Artemis  [Serious Issue][solved(kinda)]

### ISSUE THREAD

**Issue by Mrwebente** [SpoinkyNL/Artemis#344] opened 2017-04-16 20:27 UTC
so i just did the Creators update of Windows and now Artemis refuses to start...  which makes me sad because the program is so good

**Comment by SpoinkyNL** [comment] 2017-04-16 20:37
Hey, thanks for the report. I'll get the Creators Update and fix it tomorrow


*Met vriendelijke groet,*
*Robert Beekman*

2017-04-16 22:27 GMT+02:00 Mrwebente <notifications@github.com>:

**Comment by SpoinkyNL** [comment] 2017-04-17 11:08
I've installed the creators update as well and it works fine here, did you do a clean install or an update?

If it's a clean install try installing https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679

**Comment by rakosi2** [comment] 2017-04-18 05:14
I just updated windows and the first time Artemis ran it failed
WARN|Artemis.Managers.DeviceManager|Failed enabling keyboard: Corsair RGB Keyboard 
closed and opened Artemis again and changed none to corsair and worked, had so reselect my profile because it defaulted back to Default but that's an easy fix. Checked both Stable and Dev and both work.
 I noticed that in the "Apps and Features" in Windows, it says that it reinstalled Artemis today so maybe that is why I got the problems.

**Comment by manskou** [comment] 2017-04-18 07:38
I have the creators update and Artemis works fine. The update sucks tho,
I'm getting random half-freezes (everything is unresponsive except cursor,
no alt-tab, ctrl-alt-del, or any keyboard shortcut works) and I have to
reboot every time :(

**Comment by Mrwebente** [comment] 2017-04-20 17:36
i'll try reinstalling artemis. This was an update. no clean install. Creators update killed my drivers for the onboard sound too.. -.-*

**Comment by Mrwebente** [comment] 2017-04-20 17:40
well i tried reinstalling artemis but when i clicked on the setup.exe the cursor slowe and pretty much nothing happened now window or anything but it is now installed again... but it still won't start

**Comment by KasperWadesluem** [comment] 2017-04-28 06:54
i have the same problem, after updating to Creators update, Artemis stopped working. 
when i uninstall and try to reinstall it, it asks for admin rights (SmartScreen), it creates the folders and the desktop shortcut etc. but it doesn't start up properly. you can even see an empty space for where the systray icon would normally be but as soon as i hover over it, it just goes away. i'm using a Windows 10N version and i had to manually install the media feature pack again after the update if that even makes a difference for Artemis

**Comment by rakosi2** [comment] 2017-04-29 08:37
Did you guys force the Creative Update? Because Microsoft has said that there are issues (especially for older computers) and only update via the windows updater.
https://www.theregister.co.uk/2017/04/26/stop_downloading_win10_creators_update/

**Comment by KasperWadesluem** [comment] 2017-05-03 17:18
so, apparently it is a problem with MSI Afterburner, when i close Afterburner Artemis works fine, as soon as i start Afterburner (after Artemis) Artemis crashes. maybe there's somehow a conflict with the RivaTuner Statistics Server?

**Comment by rakosi2** [comment] 2017-05-04 00:57
I have been using MSI Afterburner 4.3.0 for a while now and there is no issues on my computer. I don't install the RivaTuner because I believe that it was the cause of my ban in a game. I just installed RivaTuner 7.0.0 to test it and Artemis works fine on my computer with a Corsair keyboard.

**Comment by Mrwebente** [comment] 2017-05-04 22:06
okay so i just tried the fix proposed by KasperWadesluem, it does have a problem with MSI afterburner and i do get error messages saying something about riva tuner statistics server not beeing reachable when starting the pc ( afterburner is on autostart for me, it would be sad if i would need to decide between artemis and afterburner...

**Comment by rakosi2** [comment] 2017-05-04 22:10
@Mrwebente try to uninstall RivaTuner. Uninstalling RivaTuner just removes the FPS graph and screen recording features. I have MSI Afterburner on autostart on creators update and Artemis is working fine.

**Comment by Mrwebente** [comment] 2017-05-04 22:16
@rakosi2 okay i uninstalled it and now it works again. maybe still worth looking into if someone would have the time for it :D

**Comment by SpoinkyNL** [comment] 2017-05-04 22:19
I'm back from holiday and I'll take a look over the weekend. Im using Afterburner myself and I've not had any issues so I might need to get you a special debug version. I'll get back to you tomorrow

**Comment by KasperWadesluem** [comment] 2017-05-06 03:52
well i can confirm that RivaTuner seems to be the problem, i updated to Afterburner 4.3.0 and didn't install RivaTuner with it and Artemis runs fine now

**Comment by SpoinkyNL** [comment] 2017-05-06 22:12
Thanks for the investigating guys, I've added a fix for this. 

Artemis will now check to see if RivaTuner Statistics Server (RTSS) is installed. If it finds the RTSS installation directory it will place a profile that disables RTSS for Artemis' process (lots of programs don't work with RTSS so there are already a buttload of them included by default).

The first time it installs this profile Artemis will also kill the RTSS process but the next time it will just leave it running as it won't crash Artemis again.

#### To explain what I did to figure this out:
If you head over to ```C:\Program Files (x86)\RivaTuner Statistics Server\ProfileTemplates``` you'll see a whole lot of profiles that all contain just this:

```ini
[Hooking]
EnableHooking		= 0
```

That basically disables RTSS for that .exe, Artemis will add itself to this as well.

**Comment by SpoinkyNL** [comment] 2017-11-28 21:40
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Closed** 2019-11-15 15:14 UTC
