### ISSUE TITLE
[Bug] Missing UI 

### ISSUE THREAD

**Issue by techy105** [SpoinkyNL/Artemis#182] opened 2016-10-23 16:57 UTC
Hey,
Ive encountered a bug where the UI elements on the Edit X screen don't display.
I use a G910 Keyboard. 
Artemis is running in the background in the tray, with no window open.
I open a Artemis window by double clicking the tray icon.
I go to Effects.
I double click a layer to edit it.

It seems the at UI elements are actually there but just not displaying. I can prove this by hovering my mouse over the Layer Name field (or where it would be) and my cursor changes to the word selection. I can also paste into the invisible field. This seems to occur when editing any layer.

![possiblebug](https://cloud.githubusercontent.com/assets/10698679/19627878/409b0cac-9949-11e6-8213-b77fabaf8969.jpg)

The logs dont seem to show any errors (even in debug and trace mode).

The program was started manually after boot. This was resolved after restarting the program. 

I have a feeling that this is just my PC being stupid (Windows 10 Pro x64 | R9 280X (CrossFire))

**Comment by SpoinkyNL** [comment] 2016-10-24 14:21
Hey, I've not been able to reproduce this myself. Could you try updating your video drivers and see how that goes?

**Comment by KIN0025** [comment] 2016-11-05 13:38
I have reproduced this - closing and reopening the program seems to fix it. While this happens the games panel displays nothing.
1. Open a copy of Artemis. Leave the window open.
2. Open another copy of Artemis. Close both windows.
3. Open both copies of Artemis by double clicking on the tray icons.
4. Open a layer, or go to the games tab.

Could not reproduce if opening by right clicking and selecting show Artemis. After closing the bugged windows, the option remains stuck on "Hide Artemis" for both instances until closed using the tray icon.

Reproduced on Windows 10 Pro 1607 x64 with a GTX 970M.

**Comment by SpoinkyNL** [comment] 2016-11-05 13:41
I came across it myself the other day too, while running a single instance. I have to note Artemis isn't really supposed to be ran twice. There was a check to prevent that but it was causing issues with the auto-update.

I'll look into a permanent fix nonetheless

**Comment by KIN0025** [comment] 2016-11-05 13:42
Yeah I know - read the message, but was the only way I could reliably reproduce.

**Comment by SpoinkyNL** [comment] 2016-11-05 14:02
Yeah I hope that'll send me in the right direction, thanks :+1:

**Comment by SpoinkyNL** [comment] 2016-11-11 23:05
So while adding GTAV support this was happening more and more and I couldn't figure out why.
After debugging for two full days it turns out the UI framework I'm using couldn't handle being initialized as a tray icon application.

So I changed the way the tray icon works in relation to the windows and their states, and it seems to be fully fixed now, so you can expect this fixed in the next release, which will be soon :)

**Closed** 2016-11-15 23:49 UTC
Labels: bug
