### ISSUE TITLE
Program crash - Edit colour for headset

### ISSUE THREAD

**Issue by techy105** [SpoinkyNL/Artemis#351] opened 2017-04-27 18:15 UTC
When editing a colour for a headset, clicking in the hex colour box, and copying the value by hitting CTRL + C (3 times), Artemis crashes.

Event Viewer says:
 

   Application: Artemis.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Runtime.InteropServices.COMException at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32, IntPtr) at System.Windows.Clipboard.Flush() at System.Windows.Clipboard.CriticalSetDataObject(System.Object, Boolean) at System.Windows.Clipboard.SetDataInternal(System.String, System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()

**Comment by rakosi2** [comment] 2017-04-29 16:49
I can confirm, Artemis has broke at ViewModels/ProfileEditorViewModel.cs line 331

System.Runtime.InteropServices.COMException occurred
  HResult=0x800401D0
  Message=OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at Artemis.ViewModels.ProfileEditorViewModel.<LayerToClipboard>b__61_0() in D:\Documents\Artemis-development\Artemis\Artemis\ViewModels\ProfileEditorViewModel.cs:line 331
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by SpoinkyNL** [comment] 2017-04-29 17:08
Thanks for the report, I'll get on it when I can (going on holiday tomorrow
for a short week)

Op 29 apr. 2017 18:49 schreef "rakosi2" <notifications@github.com>:

**Comment by SpoinkyNL** [comment] 2017-05-06 22:07
Hey, please let me know if it's fixed with the latest release

**Comment by rakosi2** [comment] 2017-05-06 23:00
Button smashed Ctrl-C and it didn't crash so it looks like it's fixed, thanks.

**Closed** 2017-11-28 21:39 UTC
