### ISSUE TITLE
Directory crashes

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#284] opened 2017-01-17 05:29 UTC
When I hit the 3 dotted button for the Directory, Artemis crashes.

An unexpected error occurred in Artemis.

Exception has been thrown by the target of an invocation.

Object reference not set to an instance of an object.
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Caliburn.Micro.ActionMessage.<>c.<.cctor>b__33_0(ActionExecutionContext context)
   at Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.NullReferenceException

Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Artemis.Modules.Games.EurotruckSimulator2.EurotruckSimulator2ViewModel.BrowseDirectory() in D:\Documents\Artemis-development\Artemis\Artemis\Modules\Games\EurotruckSimulator2\EurotruckSimulator2ViewModel.cs:line 23

TargetSite:
Void BrowseDirectory()

Source:
Artemis

HResult:
-2147467261

**Comment by SpoinkyNL** [comment] 2017-01-17 18:46
Will look into this one when adding ATS

**Comment by rakosi2** [comment] 2017-01-18 09:27
I should mention that my Steam is installed on my C: drive while my main Steam Library is on the D: drive along with ATS and ETS2. I thought I would say that because I think that GeneralHelpers.FindSteamGame will fail.

**Comment by rakosi2** [comment] 2017-01-22 03:51
Thank you, Artemis auto-found my games. The one thing is that if I manually try to locate the game folder using the three dotted button, Artemis selects one directory up and tells me that it could not find game. Temporarily fix by selecting plugins folder and did not error.
ex: Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64
to: Steam\steamapps\common\Euro Truck Simulator 2\bin\

**Comment by rakosi2** [comment] 2017-01-24 06:01
Thank you for fixing it for ETS2 but it is still happening for ATS too.

**Comment by SpoinkyNL** [comment] 2017-01-24 11:25
I believe that was caused by something else, can you try with the latest dev build?

**Comment by rakosi2** [comment] 2017-01-26 01:47
It is still happening.
![capture](https://cloud.githubusercontent.com/assets/6037087/22317075/4220e598-e326-11e6-8cca-6f038e1b4404.PNG)

**Comment by SpoinkyNL** [comment] 2017-01-26 10:57
This is fixed in [1.8.0.0](https://github.com/SpoinkyNL/Artemis/releases/tag/1.8.0.0). If there are still any problems with it don't hesitate to open a new issue :)

**Closed by SpoinkyNL** 2017-01-26 10:57 UTC
Labels: bug
