### ISSUE TITLE
NZXT Hue+ and/or Asus Aura support?

### ISSUE THREAD

**Issue by Sokonomi** [SpoinkyNL/Artemis#181] opened 2016-10-22 11:06 UTC
I came across this wonderful app yesterday and ive been loving it!
Though ive been wondering, can it potentially do more?

I know Asus Aura (motherboard RGB header) has an SDK to allow programs such as Artemis to feed it RGB commands to control the motherboards onboard lights as well as the 5050 LED strip header thats on it. If Artemis could support this the same way it supports general logitech gear, I could have it control my entire desk. ;)

Another thing id love to see support for, is the NZXT Hue+, a controller with serialized RGB LED strips you can operate individually.

If its not too difficult, could you have a look at these? ;-)

**Comment by LokeYourLord** [comment] 2016-10-23 10:20
Ye ASUS AURA is something i would like to, though for me it is ASUS AURA due to my Graphics Card, the GTX 1080. There is a seperate Audio Visualization mode for it in the AURA RGB software however, so it would more be for colour sync and being able to choose the colour range.

**Comment by Sokonomi** [comment] 2016-10-23 10:53
A lot of Asus strix and ROG products use the AURA protocol, and it has an API to hook into, so supporting it would add a nice range of products I think.

**Comment by SpoinkyNL** [comment] 2016-10-23 11:13
Hey, should be relatively easy to add as a generic device. 

I'll look into it when I have the time :)

**Comment by dennild** [comment] 2017-01-06 15:17
i would love this and now that Razer have opened op their API ( from what i could understand) this would be awesome.

**Comment by SpoinkyNL** [comment] 2017-01-06 15:52
If someone could link me to the actual API's I'll take a look. I did some Googling before but couldn't find anything.

**Comment by dennild** [comment] 2017-01-06 16:46
http://developer.razerzone.com/works-with-chroma/download/ 

Found this but they might not have relased the new thing they just announced on CES2017 yet.

**Comment by Semyntax** [comment] 2017-01-07 17:58
NZXT hue+ is controlled via COM device. 
https://github.com/kusti8/hue-plus/blob/master/hue.py

**Comment by Semyntax** [comment] 2017-01-23 01:29
I couldn't find any documentation or SDK for ASUS Aura. So I partially reverse engineered the Aura Application for VGA. Anyone feel free to use, modify or include this for your projects, you will need the Vender.dll and VGA_Extra.dll from "AURA(GRAPHICS CARD)" in order to work.

The Aura App sometimes uses a 200ms Sleep() after Calls to Set_LED_ExternalFan_Info(), since rapidly changing the lights might cause some delay and the next attempt to change the color or disable the lights might just be ignored.

```C#
using System;
using System.Runtime.InteropServices;

namespace AsusVgaAura
{
    public enum LightingMode : UInt32
    {
        None = 0x00,
        Static = 0x01,
        Breath = 0x02,
        Strobe = 0x03,
        CrossfadeColorSpectrum = 0x04
    }
    [StructLayout(LayoutKind.Explicit)]
    public struct LedColor
    {
        [FieldOffset(0)]
        public UInt32 Red;
        [FieldOffset(4)]
        public UInt32 Green;
        [FieldOffset(8)]
        public UInt32 Blue;
    }
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct InteropLedInfo
    {
        [FieldOffset(0)]
        public UInt32 Unknown1;

        [FieldOffset(4)]
        public UInt32 Unknown2;

        [FieldOffset(8)]
        public UInt32 Unknown3;

        /// <summary>
        /// Unsure, Is always 0x01
        /// </summary>
        [FieldOffset(12)]
        public UInt32 Unknown4;

        [FieldOffset(16)]
        public LedColor Color;

        /// <summary>
        /// needs to be 0x01 in order to disable LEDs or change LightingMode
        /// </summary>
        [FieldOffset(28)]
        public UInt32 ChangeState;

        [FieldOffset(32)]
        public LightingMode Mode;
    };

    public class AsusVgaAuraWrapper
    {
        [DllImport(dllName: "VGA_Extra.dll", CallingConvention = CallingConvention.Cdecl)]
        public static extern void LoadVenderDLL();

        [DllImport(dllName: "VGA_Extra.dll", CallingConvention = CallingConvention.Cdecl)]
        public static extern void Set_LED_ExternalFan_Info(InteropLedInfo ledInfo);

        public AsusVgaAuraWrapper()
        {
            LoadVenderDLL();
        }

        public void SetColor(byte red, byte green, byte blue, LightingMode lightingMode = LightingMode.Static)
        {
            InteropLedInfo data = new InteropLedInfo();
            data.Unknown4 = 0x01;
            data.Color.Red = red;
            data.Color.Green = green;
            data.Color.Blue = blue;
            data.ChangeState = 0x01;
            data.Mode = lightingMode;
            Set_LED_ExternalFan_Info(data);
        }

        public void DisableLights()
        {
            InteropLedInfo data = new InteropLedInfo();
            data.Unknown4 = 0x01;
            data.Color.Red = 0x00;
            data.Color.Green = 0x00;
            data.Color.Blue = 0x00;
            data.ChangeState = 0x01;
            Set_LED_ExternalFan_Info(data);
        }
    }
}

**Comment by Stasadance** [comment] 2017-01-31 19:17
@Semyntax any luck on reverse engineering the ASUS Strix motherboard (LED_DLL_forMB.dll) too? Would complete the set for ASUS and then I can make an unofficial Strix SDK! I've tried but with no luck, it maybe has some protection or something. I'm new to reflection like this so it would be a big help.

**Comment by Semyntax** [comment] 2017-01-31 21:03
@Stasadance my current ASUS board does not support aura. I already tried, but in order get the whole picture I need to debug through the aura application in action. By looking at the DLL exports I guess fnEnumSupportDevice and fnApplySetting aswell as fnSetLEDBurn/Color/EFFECT/Frame/ON might also be involved. I tried Snowman as well but I have trouble Interpreting the gibberish it generates. But you may try it yourself using x64dbg or ollydbg. Find functions in the DLL that are actually called, and look at the instructions before the call ( especially push and mov instructions ). Also debug into the code of DLL and look how the parameters are used (pointers to data on the stack [register + offset], eg [esp +8]). You will need some basic assembler knowledge though.

**Comment by Stasadance** [comment] 2017-02-01 00:40
@Semyntax OK Thanks, I did get fnSetLEDColor working as im pretty good with basic buffer types and whatnot, but I have not been able to get it to work still, just doesn't change colors on my Strix MB, In x32dbg I can't seem to figure out how to see what gets called during debug but it seems like the Aura service itself and not Aura.exe is doing the setting now.., but I cannot debug the service! 😩

**Comment by SpoinkyNL** [comment] 2017-02-01 00:59
If you guys got it working, feel free to implement it as a generic device :) 

It's quite simple, take a look at the Logitech one: https://github.com/SpoinkyNL/Artemis/blob/master/Artemis/Artemis/DeviceProviders/Logitech/LogitechGeneric.cs

No knowledge of Artemis's inner workings required :3

**Comment by VictorStagnetty** [comment] 2017-02-11 00:14
Anyway to control(or have ASUS Aura control) NZXT AER RGB fans? Or do you have to buy the HUE+ thing. I would LOVE to use these sexy fans, but they are pricey already. If i have to buy the HUE+ the price is insane for some fans that don't perform as good as many other fans on the market. I know absolutely nothing about programing.

**Comment by Stasadance** [comment] 2017-02-11 00:17
@VictorStagnetty it is definitely possible, if all you need to do is control them fans only. If not, the issue is that since my last comment, I haven't been able to change the motherboard colors and its RGB headers at all, so if that's what you are going for, we have to wait for an SD from ASUS or some reverse engineering god to come help. 😄

**Comment by CalcProgrammer1** [comment] 2017-02-14 21:02
I'm interested in Aura support in my own app, Keyboard Visualizer, as well.  I have a contributor who reverse engineered the Hue+, @Bl4d3s.  We're discussing Aura reverse engineering in an issue here https://github.com/CalcProgrammer1/KeyboardVisualizer/issues/85, mainly as it pertains to motherboards and RGB RAM.  I don't own these yet but I plan to with Ryzen's release (Crossfire X370 and GSkill Trident Z RGB).  I can help R/Eing then.  I'm all for spreading knowledge about RGB devices so we can all support as many devices as possible.

**Comment by Stasadance** [comment] 2017-02-14 21:10
Thats great, maybe we should take this issue into a custom repo and combine what we know. I can provide DLL's and what not as well as testing as I have all the Aura sync hardware myself.

**Comment by CalcProgrammer1** [comment] 2017-02-14 21:25
That would be nice.  Figuring out how the DLLs work and using them in our own apps is a good start, but I would also like to dig down to the hardware for the possibility of a Linux implementation.  I'm curious as to what bus these motherboard/GPU/RAM based RGB controllers use.  If I had to guess, I'd say I2C.

**Comment by WSorban** [comment] 2017-02-24 13:57
Hello guys,
I have developed a service that listens on UDP Port 30303, and changes the RGB lights of the Razer peripherals, using an Android App: Android Razer Control (developed by somebody else), which can be found here:
https://play.google.com/store/apps/details?id=com.howesthatapp.mike.razerconfigurator
There is also a friend, who decompiled the Asus GPU code, and sent it to me.
You can see his demo here:
https://www.youtube.com/watch?v=37iOmKfJJPs
The video uploader sent me the code and DLL's, and I implemented that also, into my Service.
You can find the source code, and the service executable below:
https://github.com/WSorban/RGBService﻿

Since I do not own the GPU (nor wish to have it), since I am using custom water cooling, I only have the Asus Z270 Formula IX, and been trying to figure a way to get the DLLs and addresses of the RGB controllers of this board, but so far have been unsuccessful.

Have a go at my code, if you wish, and feel free to make improvements!
Show less

**Comment by SpoinkyNL** [comment] 2017-02-24 14:08
As I don't own any of this hardware and I don't really see anyone looking to make a PR this doesn't really have much to do with Artemis anymore.

I'll close this now, feel free to make a PR with support for this ofcourse :).

**Closed by SpoinkyNL** 2017-02-24 14:08 UTC
Labels: device request
