### ISSUE TITLE
Default profile placement broken

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#411] opened 2017-11-30 18:52 UTC
The ZIP contains a folder in which all the keyboard folders are. This is wrong, they should be in the root of the ZIP instead

**Comment by Rechinan** [comment] 2017-12-02 14:33
Would this be why I can’t see any default profiles, don’t want to open a new issue if it’s a duplicate of this?

**Comment by SpoinkyNL** [comment] 2017-12-03 08:49
Very likely, I meant to fix this ASAP but some things came up, hopefully
today I'll put out a release

Op 2 dec. 2017 15:33 schreef "Squeak" <notifications@github.com>:

**Closed** 2019-11-15 15:14 UTC
