### ISSUE TITLE
Logitech G910 orion spark couldn't connect 

### ISSUE THREAD

**Issue by Leon6er** [SpoinkyNL/Artemis#450] opened 2018-06-04 03:46 UTC
so recently I was trying to set up my keyboard ((G910 Orion spark)) on this program but it seems like it really doesn't want to work even though it's up to date. ((both the Lgs Artemis and c++)) 
whenever I try to set it up as my keyboard I get this response 

"couldn't  connect to your Logitech keyboard 
please check your cables and updating the Logitech gaming software 
a minimum version of 8;.81.15 is required (detected 9.0.42) "

**Comment by Zeouls** [comment] 2018-06-07 14:34
I got the same issue, with the exact same error message, any ideas yet?

**Comment by InflamedSebi** [comment] 2018-06-09 18:52
same issue here. reinstalling did not help.

**Comment by Zeouls** [comment] 2018-06-11 12:53
Hopefully soon enoug someone will anser :/

**Comment by HazardDev** [comment] 2018-06-11 21:31
Hi there, could you try using version 8 of the logitech software (at least 8.81.15) instead of version 9? I have a suspicion that the issue is not the device, but the Logitech API we're using. Perhaps the release of a v2 Orion Spark also came with a new version of the logitech software that is having issues.

**Comment by HazardDev** [comment] 2018-06-11 21:32
This is probably a dupe of #449

**Comment by Zeouls** [comment] 2018-06-12 06:20
Tried the version 8.81.15 logitech software doesnt recognize keyboard my keyboard anymore

**Comment by DarthAffe** [comment] 2018-06-12 09:58
There was most likely also a firmware update. The new version of the logitech SDK supports "Zones" for some devices, I'd expect this to be a breaking feature for previous versions.

**Comment by Zeouls** [comment] 2018-06-12 13:56
I guess I now know why it doesnt work. As DarthAffe said there is now "Zones" and well I got the new G910 Version 2 which exactly as he said supports "Zones" which might be the issue.

**Comment by SpoinkyNL** [comment] 2018-06-12 20:12
Hi, please try with the latest version and let me know if it works again :)

**Comment by Zeouls** [comment] 2018-06-13 09:03
Issue seems to be fixed

**Closed** 2019-11-15 15:11 UTC
Labels: bug
